routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@homepage');
Route::get('http://www.filipecruz.com.br/', 'HomeController@home');

Route::post('/contato', 'HomeController@contact')->name('contact');
Route::post('/blog/commentario', 'BlogController@comment')->name('comment');

// API

Route::get('/api/tags', 'Admin\TagController@tagsName');

Route::get('/api/posts', 'Admin\PostController@posts');
Route::get('/api/posts/{id}', 'Admin\PostController@postInfo');

Route::get('/contato', 'BlogController@contato')->name('contato');

Route::get('/blog/busca', 'BlogController@busca')->name('busca');


Auth::routes();

// Redirect route register
Route::match(['get', 'post'], 'register', function(){
    return redirect('/');
});

Route::get('/admin', 'AdminController@index')->name('admin');

Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function() {

    // Pages
    Route::resource('paginas', 'PageController');
    Route::get('/paginas', 'PageController@index')->name('paginas');
    Route::get('/pagina/criar', 'PageController@create')->name('criar.paginas');
    Route::get('/pagina/{id}/editar', 'PageController@show')->name('editar.paginas');

    // Posts
    Route::resource('artigos', 'PostController');
    Route::get('/artigos', 'PostController@index')->name('artigos');
    Route::get('/artigo/criar', 'PostController@create')->name('criar.artigos');
    Route::get('/artigo/{id}/editar', 'PostController@show')->name('editar.artigos');

    // Tags
    Route::resource('tags', 'TagController');
    Route::get('/tags', 'TagController@index')->name('tags');
    Route::get('/tag/criar', 'TagController@create')->name('criar.tags');
    Route::get('/tag/{id}/editar', 'TagController@show')->name('editar.tags');

    // Categorias
    Route::resource('categorias', 'CategoryController');
    Route::get('/categorias', 'CategoryController@index')->name('categorias');
    Route::get('/categoria/criar', 'CategoryController@create')->name('criar.categorias');
    Route::get('/categoria/{id}/editar', 'CategoryController@show')->name('editar.categorias');

    // Usuários
    Route::resource('usuarios', 'UserController');
    Route::get('/usuarios', 'UserController@index')->name('usuarios');
    Route::get('/usuario/criar', 'UserController@create')->name('criar.usuarios');
    Route::get('/usuario/{id}/editar', 'UserController@show')->name('editar.usuarios');

    // Comentários
    Route::resource('comentarios', 'CommentController');
    Route::get('/comentarios', 'CommentController@index')->name('comentarios');
    Route::get('/comentario/{id}/editar', 'CommentController@show')->name('editar.comentarios');

    // Comentários
    Route::resource('contatos', 'ContactController');
    Route::get('/contatos', 'ContactController@index')->name('contatos');

    // Comentários
    Route::resource('configuracoes', 'OptionController');
    Route::get('/configuracoes', 'OptionController@index')->name('configuracoes');

    // Medias
    Route::get('/midias/imagens', function () {
        return view('admin.media.image');
    });
    Route::get('/midias/arquivos', function () {
        return view('admin.media.file');
    });

    // Estatísticas
    Route::get('/estatisticas/visualizacoes/{date}', 'StatisticController@viewsByDate');
    Route::get('/estatisticas/{days}', 'StatisticController@statistics');
});

Route::get('blog', 'BlogController@home');

Route::get('blog/{slug}', 'BlogController@getPost');

Route::get('{slug}', 'HomeController@getPage');

Route::get('blog/categoria/{category}', 'BlogController@category');

Route::get('blog/tag/{tag}', 'BlogController@tag');

resources/views/admin/page/create.blade.php
@extends('adminlte::page')

@section('title', 'Filipe Cruz - Todas as Páginas')

@section('content_header')
    <title-header title='Adicionar nova página'></title-header>
    <breadcrumbs :list="{{ $breadcrumbs }}"></breadcrumbs>
@stop

@section('content')


    <form-head id="createForm" css="" action="{{ route('paginas.store') }}" method="post" enctype="" token="{{ csrf_token() }}">
        <input type="hidden" id="author_id" name="author_id" value="{{ Auth::user()->id }}">

        <div class="row">
            <!-- Template default -->
            @include('templates.page.default')

            <div class="col-md-3">
                <panel title="Publicar" css="info">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-eye"></i></span>
                            <select class="form-control input-sm" id="status" name="status">
                                <option value="draft">Rascunho</option>
                                <option value="published">Publicado</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <select class="form-control input-sm" id="date" name="date">
                                <option value="">Imediatamente</option>
                                <option value="schedule">Agendar</option>
                            </select>
                        </div>
                    </div>
                    <date></date>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default btn-flat bg-blue">
                            Publicar
                        </button>
                    </div>
                </panel>
                <panel title="Atributos da página" css="info">
                    <div class="form-group">
                        <label for="parent_id">Pai</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-level-up"></i>
                            </div>
                            <select class="form-control input-sm" id="parent_id" name="parent_id">
                                <option value="">(sem pai)</option>
                                @foreach($pages as $key => $value)
                                    <option value="{{ $value->id }}">{{ $value->title }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <template-select></template-select>
                </panel>
                <panel title="Imagem de Destaque" css="info">
                    <upload name="imagem"></upload>
                </panel>
            </div>
        </div>
    </form-head>

@stop

@section('script')
    <script>
        $(window).on('load', function() {

            $('#date').change(function () {
                if ($(this).val() == '') {
                    $('#publishDate').hide();
                } else {
                    $('#publishDate').show();
                }
            });
        });
    </script>
@stop

resources/views/admin/page/edit.blade.php
@extends('adminlte::page')

@section('title', 'Filipe Cruz - Todas as Páginas')

@section('content_header')
    <title-header title='Editar página'></title-header>
    <breadcrumbs :list="{{ $breadcrumbs }}"></breadcrumbs>
@stop

@section('content')

    @php($action =  route('paginas') . '/' . $collection->id )
    <form-head id="createForm" css="" action="{{ $action }}" method="put" enctype="" token="{{ csrf_token() }}">
        <input type="hidden" id="author_id" name="author_id" value="{{ $collection->author_id }}">
        <div class="row">

            <!-- Template default -->
            @php($template = 'templates.page.' . $collection->type)
            @include($template, array('collection'=>$collection))

            <div class="col-md-3">
                <panel title="Publicar" css="info">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-eye"></i></span>
                            <select class="form-control input-sm" id="status" name="status">
                                @if($collection->status === 'draft')
                                    <option value="draft">Rascunho</option>
                                @else
                                    <option value="published">Publicado</option>
                                @endif
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <select class="form-control input-sm" id="date" name="date">
                                @if($collection->status !== 'schedule')
                                    <option value="" selected>Imediatamente</option>
                                    <option value="schedule">Agendado</option>
                                @else
                                    <option value="">Imediatamente</option>
                                    <option value="schedule" selected>Agendado</option>
                                @endif
                            </select>
                        </div>
                    </div>
                    <date datetime="{{ $collection->date }}"></date>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default btn-flat bg-blue">
                            Atualizar
                        </button>
                    </div>
                </panel>
                <panel title="Atributos da página" css="info">
                    <div class="form-group">
                        <label for="parent_id">Pai</label>
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-level-up"></i>
                            </div>
                            <select class="form-control input-sm" id="parent_id" name="parent_id">
                                <option value="">(sem pai)</option>
                                @foreach($pages as $key => $value)
                                    @if($collection->parent_id === $value->id)
                                        <option value="{{ $value->id }}" selected>{{ $value->title }}</option>
                                    @else
                                        <option value="{{ $value->id }}">{{ $value->title }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <template-select template="{{ $collection->type }}"></template-select>
                </panel>
                <panel title="Imagem de Destaque" css="info">
                    <upload id="imagem" name="imagem" image="{{ $collection->image }}"></upload>
                </panel>
            </div>
        </div>
    </form-head>

@stop

@section('script')
    <script>
        $(window).on('load', function() {

            $('#date').change(function () {
                if ($(this).val() == '') {
                    $('#publishDate').hide();
                } else {
                    $('#publishDate').show();
                }
            });
        });
    </script>
@stop

resources/views/admin/page/index.blade.php
@extends('adminlte::page')

@section('title', 'Filipe Cruz - Todas as Páginas')

@section('content_header')
    <title-header title='Páginas'></title-header>
    <breadcrumbs :list="{{ $breadcrumbs }}"></breadcrumbs>
@stop

@section('content')
    <panel title="Gerenciamento de páginas" css="info">
        <box-header create="{{ route('criar.paginas') }}" token="{{ csrf_token() }}"></box-header>
        <data-table
                name="tablePages"
                :titles="[['#', ''],['Título','string'],[ 'Autor',''],['Status',''],[ 'Comentários','number'],[ 'Criação',''],[ 'Agendado','icon'], ['Slug', '']]"
                :content="{{ json_encode($collection) }}"
                edit="{{ route('paginas') }}"
                exclude="{{ route('paginas') }}"
                token="{{ csrf_token() }}"
                urlview="true"
        ></data-table>
        <div class="box-footer clearfix">
            <div class="float-right my-2">
                <div class="pull-right">
                    {{ $collection->links() }}
                </div>
            </div>
        </div>
    </panel>

@stop