routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@homepage');
Route::get('http://www.filipecruz.com.br/', 'HomeController@home');

Route::post('/contato', 'HomeController@contact')->name('contact');
Route::post('/blog/commentario', 'BlogController@comment')->name('comment');

// API

Route::get('/api/tags', 'Admin\TagController@tagsName');

Route::get('/api/posts', 'Admin\PostController@posts');
Route::get('/api/posts/{id}', 'Admin\PostController@postInfo');

Route::get('/contato', 'BlogController@contato')->name('contato');

Route::get('/blog/busca', 'BlogController@busca')->name('busca');


Auth::routes();

// Redirect route register
Route::match(['get', 'post'], 'register', function(){
    return redirect('/');
});

Route::get('/admin', 'AdminController@index')->name('admin');

Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function() {

    // Pages
    Route::resource('paginas', 'PageController');
    Route::get('/paginas', 'PageController@index')->name('paginas');
    Route::get('/pagina/criar', 'PageController@create')->name('criar.paginas');
    Route::get('/pagina/{id}/editar', 'PageController@show')->name('editar.paginas');

    // Posts
    Route::resource('artigos', 'PostController');
    Route::get('/artigos', 'PostController@index')->name('artigos');
    Route::get('/artigo/criar', 'PostController@create')->name('criar.artigos');
    Route::get('/artigo/{id}/editar', 'PostController@show')->name('editar.artigos');

    // Tags
    Route::resource('tags', 'TagController');
    Route::get('/tags', 'TagController@index')->name('tags');
    Route::get('/tag/criar', 'TagController@create')->name('criar.tags');
    Route::get('/tag/{id}/editar', 'TagController@show')->name('editar.tags');

    // Categorias
    Route::resource('categorias', 'CategoryController');
    Route::get('/categorias', 'CategoryController@index')->name('categorias');
    Route::get('/categoria/criar', 'CategoryController@create')->name('criar.categorias');
    Route::get('/categoria/{id}/editar', 'CategoryController@show')->name('editar.categorias');

    // Usuários
    Route::resource('usuarios', 'UserController');
    Route::get('/usuarios', 'UserController@index')->name('usuarios');
    Route::get('/usuario/criar', 'UserController@create')->name('criar.usuarios');
    Route::get('/usuario/{id}/editar', 'UserController@show')->name('editar.usuarios');

    // Comentários
    Route::resource('comentarios', 'CommentController');
    Route::get('/comentarios', 'CommentController@index')->name('comentarios');
    Route::get('/comentario/{id}/editar', 'CommentController@show')->name('editar.comentarios');

    // Comentários
    Route::resource('contatos', 'ContactController');
    Route::get('/contatos', 'ContactController@index')->name('contatos');

    // Comentários
    Route::resource('configuracoes', 'OptionController');
    Route::get('/configuracoes', 'OptionController@index')->name('configuracoes');

    // Medias
    Route::get('/midias/imagens', function () {
        return view('admin.media.image');
    });
    Route::get('/midias/arquivos', function () {
        return view('admin.media.file');
    });

    // Estatísticas
    Route::get('/estatisticas/visualizacoes/{date}', 'StatisticController@viewsByDate');
    Route::get('/estatisticas/{days}', 'StatisticController@statistics');
});

Route::get('blog', 'BlogController@home');

Route::get('blog/{slug}', 'BlogController@getPost');

Route::get('{slug}', 'HomeController@getPage');

Route::get('blog/categoria/{category}', 'BlogController@category');

Route::get('blog/tag/{tag}', 'BlogController@tag');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Tag extends Model
{
    protected $table = 'tags';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name','slug'
    ];

    public $timestamps = false;

    public function posts()
    {
        return $this->belongsToMany('App\Post', 'tag_post');
    }

    public static function getTags($page_size)
    {
        return DB::table('tags')->paginate($page_size);
    }

    public static function getTagsNames()
    {
        return DB::table('tags')->select('name')->get();
    }

    public static function search($term)
    {
        return DB::table('tags')
            ->where('name', 'like', "%". strtolower($term) . "%")
            ->distinct()
            ->paginate(25);
    }

}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Tag;
use Validator;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin'), 'icon' => 'dashboard'],
            ['title' => 'Tags', 'icon' => 'tags'],
        ]);

        $search = $request->busca;

        if(empty($search)) {
            $collection = Tag::getTags(10);
        } else {
            $collection = Tag::search($search);
        }



        return view('admin.tag.index', compact('collection', 'breadcrumbs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin'), 'icon' => 'dashboard'],
            ['title' => 'Tags', 'url' => route('tags'), 'icon' => 'tags'],
            ['title' => 'Nova Tag', 'url' => '', 'icon' => 'tags'],
        ]);

        $tags = Tag::all();

        return view('admin.tag.create', compact('breadcrumbs', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       return self::verifyData($request->all(), null);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin'), 'icon' => 'dashboard'],
            ['title' => 'Tags', 'url' => route('tags'), 'icon' => 'tags'],
            ['title' => 'Editar Tag', 'url' => '', 'icon' => 'tags'],
        ]);
        $collection = Tag::find($id);
        $tags = Tag::all();

        return view('admin.tag.edit', compact('collection','tags','breadcrumbs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return self::verifyData($request->all(), $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tag::find($id)->delete();

        return redirect()->back();
    }

    private static function verifyData($data, $id)
    {
        $unique = '';
        if(!empty($id)) {
            $unique = ',name,'.$id;
        }

        $rules = [
            'name' => 'required|max:100|unique:tags' . $unique,
            'slug'  => 'required',
        ];

        $messages = [
            'name.required' => 'O campo nome é obrigatório',
            'name.unique'    => 'Esta tag já existe',
            'slug.required'    => 'O slug é obrigatório',
        ];

        $validator = Validator::make($data, $rules, $messages);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $data['slug'] = str_slug($data['slug']);

        if(empty($id)):
            Tag::create($data);
        else:
            Tag::find($id)->update($data);
        endif;

        return redirect()->route('tags');

    }

    public function tagsName()
    {
        $tags = Tag::getTagsNames();
        $labelTags = [];
        foreach ($tags as $key => $tag) {
            array_push($labelTags, $tag->name);
        }
        sort($labelTags);
        return $labelTags;
    }

}

resources/views/admin/tag/edit.blade.php
@extends('adminlte::page')

@section('title', 'Filipe Cruz - Todas as Tags')

@section('content_header')
    <title-header title='Editar tag'></title-header>
    <breadcrumbs :list="{{ $breadcrumbs }}"></breadcrumbs>
@stop

@section('content')
    @include('layouts.alert', ['errors', $errors])
    @php($action =  route('tags') . '/' . $collection->id)
    <form-head id="createForm" css="" action="{{ $action }}" method="put" enctype="" token="{{ csrf_token() }}">
        <div class="row">
            <div class="form-group col-md-3">
                <label for="name">Tag</label>
                <input type="text" id="name" name="name" class="form-control" placeholder="Nome da tag" value="{{ $collection->name }}" style=" width: 100%;">
            </div>
            <div class="form-group col-md-3">
                <label for="slug">Slug</label>
                <input type="text" id="slug" name="slug" class="form-control" placeholder="{{ URL::to('/') }}/blog/slug-da-tag" value="{{ $collection->slug }}" style=" width: 100%;">
            </div>
            <div class="form-group col-md-3">
                <label>&nbsp</label>
                <button type="submit" class="btn btn-default btn-flat bg-blue btn-block">
                    Salvar
                </button>
            </div>
        </div>
    </form-head>

@stop

@section('js')
    <script>
        $(function () {
            $("#name").focusout(function() {
                $("#slug").val($( this ).val())
            });
        })
    </script>
@stop

resources/views/admin/tag/index.blade.php
@extends('adminlte::page')

@section('title', 'Filipe Cruz - Todas as Páginas')

@section('content_header')
    <title-header title='Tags'></title-header>
    <breadcrumbs :list="{{ $breadcrumbs }}"></breadcrumbs>
@stop

@section('content')
    @include('layouts.alert', ['errors', $errors])
    <panel title="Adicionar de tags" css="success">
        <form-head id="createForm" css="" action="{{ route('tags.store') }}" method="post" enctype="" token="{{ csrf_token() }}">
            <div class="row">
                <div class="form-group col-md-3">
                    <label for="name">Tag</label>
                    <input type="text" id="name" name="name" class="form-control" placeholder="Nome da tag" value="{{ old('name') }}" style=" width: 100%;">
                </div>
                <div class="form-group col-md-3">
                    <label for="slug">Slug</label>
                    <input type="text" id="slug" name="slug" class="form-control" placeholder="{{ URL::to('/') }}/blog/slug-da-tag" value="{{ old('slug') }}" style=" width: 100%;">
                </div>
                <div class="form-group col-md-2">
                    <label>&nbsp</label>
                    <button type="submit" class="btn btn-default btn-flat bg-blue btn-block">
                        Adicionar
                    </button>
                </div>
            </div>
        </form-head>
    </panel>

    <panel title="Lista de tags" css="info">
        <box-header token="{{ csrf_token() }}"></box-header>
        <data-table
                name="tablePages"
                :titles="[['#', ''],['Nome','string'],[ 'Slug','']]"
                :content="{{ json_encode($collection) }}"
                edit="{{ route('tags') }}"
                exclude="{{ route('tags') }}"
                token="{{ csrf_token() }}"
        ></data-table>
        <div class="box-footer clearfix">
            <div class="float-right my-2">
                <div class="pull-right">
                    {{ $collection->links() }}
                </div>
            </div>
        </div>
    </panel>

@stop

@section('js')
    <script>
        $(function () {
            $("#name").focusout(function() {
                $("#slug").val($( this ).val())
            });
        });

    </script>
@stop