routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@homepage');
Route::get('http://www.filipecruz.com.br/', 'HomeController@home');

Route::post('/contato', 'HomeController@contact')->name('contact');
Route::post('/blog/commentario', 'BlogController@comment')->name('comment');

// API

Route::get('/api/tags', 'Admin\TagController@tagsName');

Route::get('/api/posts', 'Admin\PostController@posts');
Route::get('/api/posts/{id}', 'Admin\PostController@postInfo');

Route::get('/contato', 'BlogController@contato')->name('contato');

Route::get('/blog/busca', 'BlogController@busca')->name('busca');


Auth::routes();

// Redirect route register
Route::match(['get', 'post'], 'register', function(){
    return redirect('/');
});

Route::get('/admin', 'AdminController@index')->name('admin');

Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function() {

    // Pages
    Route::resource('paginas', 'PageController');
    Route::get('/paginas', 'PageController@index')->name('paginas');
    Route::get('/pagina/criar', 'PageController@create')->name('criar.paginas');
    Route::get('/pagina/{id}/editar', 'PageController@show')->name('editar.paginas');

    // Posts
    Route::resource('artigos', 'PostController');
    Route::get('/artigos', 'PostController@index')->name('artigos');
    Route::get('/artigo/criar', 'PostController@create')->name('criar.artigos');
    Route::get('/artigo/{id}/editar', 'PostController@show')->name('editar.artigos');

    // Tags
    Route::resource('tags', 'TagController');
    Route::get('/tags', 'TagController@index')->name('tags');
    Route::get('/tag/criar', 'TagController@create')->name('criar.tags');
    Route::get('/tag/{id}/editar', 'TagController@show')->name('editar.tags');

    // Categorias
    Route::resource('categorias', 'CategoryController');
    Route::get('/categorias', 'CategoryController@index')->name('categorias');
    Route::get('/categoria/criar', 'CategoryController@create')->name('criar.categorias');
    Route::get('/categoria/{id}/editar', 'CategoryController@show')->name('editar.categorias');

    // Usuários
    Route::resource('usuarios', 'UserController');
    Route::get('/usuarios', 'UserController@index')->name('usuarios');
    Route::get('/usuario/criar', 'UserController@create')->name('criar.usuarios');
    Route::get('/usuario/{id}/editar', 'UserController@show')->name('editar.usuarios');

    // Comentários
    Route::resource('comentarios', 'CommentController');
    Route::get('/comentarios', 'CommentController@index')->name('comentarios');
    Route::get('/comentario/{id}/editar', 'CommentController@show')->name('editar.comentarios');

    // Comentários
    Route::resource('contatos', 'ContactController');
    Route::get('/contatos', 'ContactController@index')->name('contatos');

    // Comentários
    Route::resource('configuracoes', 'OptionController');
    Route::get('/configuracoes', 'OptionController@index')->name('configuracoes');

    // Medias
    Route::get('/midias/imagens', function () {
        return view('admin.media.image');
    });
    Route::get('/midias/arquivos', function () {
        return view('admin.media.file');
    });

    // Estatísticas
    Route::get('/estatisticas/visualizacoes/{date}', 'StatisticController@viewsByDate');
    Route::get('/estatisticas/{days}', 'StatisticController@statistics');
});

Route::get('blog', 'BlogController@home');

Route::get('blog/{slug}', 'BlogController@getPost');

Route::get('{slug}', 'HomeController@getPage');

Route::get('blog/categoria/{category}', 'BlogController@category');

Route::get('blog/tag/{tag}', 'BlogController@tag');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'profile', 'avatar', 'description', 'twitter', 'linkedin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static function getUsers($page_size)
    {
        return DB::table('users')
            ->select('id', 'name','email', 'profile')
            ->whereNull('deleted_at')
            ->paginate($page_size);
    }

    public static function search($term)
    {
        return DB::table('users')
            ->where('name', 'like', "%". strtolower($term) . "%")
            ->orWhere('email', 'like', "%". strtolower($term) . "%")
            ->select('id', 'name','email', 'profile')
            ->distinct()
            ->paginate(25);
    }

    public function pages()
    {
        return $this->hasMany('App\Page','author_id');
    }

    public function posts()
    {
        return $this->hasMany('App\Post','author_id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Validator;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin'), 'icon' => 'dashboard'],
            ['title' => 'Usuários', 'icon' => 'users'],
        ]);

        if(empty($search)) {
            $collection = User::getUsers(10);
        } else {
            $collection = User::search($search);
        }

        return view('admin.user.index', compact('breadcrumbs', 'collection'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin'), 'icon' => 'dashboard'],
            ['title' => 'Usuários', 'url' => route('usuarios'), 'icon' => 'users'],
            ['title' => 'Novo Usuário', 'url' => '', 'icon' => 'user'],
        ]);

        $users = User::all();

        return view('admin.post.create', compact('breadcrumbs', 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $validator = Validator::make($data, [
            'name' => 'required|string|max:255',
            'email'  => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6'
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $data['password'] = bcrypt($data['password']);


        User::create($data);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin'), 'icon' => 'dashboard'],
            ['title' => 'Usuários', 'url' => route('usuarios'), 'icon' => 'users'],
            ['title' => 'Editar Usuário', 'url' => '', 'icon' => 'user'],
        ]);

        $collection = User::find($id);

        return view('admin.user.edit', compact('collection','breadcrumbs'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        if(isset($data['password']) && !empty($data['password'])):
            $validator = Validator::make($data, [
                'name' => 'required|string|max:255',
                'email'  => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($id)],
                'password' => 'required|string|min:6'
            ]);
            $data['password'] = bcrypt($data['password']);
        else:
            $validator = Validator::make($data, [
                'name' => 'required|string|max:255',
                'email'  => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($id)],
            ]);
            unset($data['password']);
        endif;

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        User::find($id)->update($data);

        return redirect()->back()->withErrors(['message', 'Usuário atualizada!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/user/create.blade.php
@extends('adminlte::page')

@section('title', 'Filipe Cruz - Todas os Usuários')

@section('content_header')
    <title-header title='Adicionar novo usuário'></title-header>
    <breadcrumbs :list="{{ $breadcrumbs }}"></breadcrumbs>
@stop

@section('content')


    <form-head id="createForm" css="" action="{{ route('usuarios.store') }}" method="post" enctype="" token="{{ csrf_token() }}">
        <div class="row">
            <panel title="Atributos da página" css="info">
                <div class="form-group">
                    <label for="parent_id">Pai</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-level-up"></i>
                        </div>
                        <select class="form-control input-sm" id="parent_id" name="parent_id">
                            <option value="">(sem pai)</option>
                        </select>
                    </div>
                </div>
                <template-blog></template-blog>
            </panel>
        </div>
    </form-head>

@stop

@section('script')
    <script>

        $(window).on('load', function() {

        });
    </script>
@stop

@section('css')
@stop

resources/views/admin/user/edit.blade.php
@extends('adminlte::page')

@section('title', 'Filipe Cruz - Todas os Usuários')

@section('content_header')
    <title-header title='Editar usuários'></title-header>
    <breadcrumbs :list="{{ $breadcrumbs }}"></breadcrumbs>
@stop

@php($profiles = ['subscriber' => 'Assinante', 'contributor' => 'Colaborador', 'author' => 'Autor', 'editor' => 'Editor' ,'administrator' => 'administrador', ])

@section('content')

    <form-head id="createForm" css="" action="{{ $action =  route('usuarios') . '/' . $collection->id }}" method="put" enctype="" token="{{ csrf_token() }}">
        <panel title="Informações do usuário" css="info">
            <div class="col-md-5 col-lg-offset-2">
                <label for="avatar"> Avatar </label>
                <upload id="avatar" name="avatar" image="{{ $collection->avatar }}"></upload>
                <div class="form-group">
                    <label class="sr-only" for="name"> Nome </label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ $collection->name }}">
                </div>
                <div class="form-group">
                    <label class="sr-only" for="email"> Email </label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="E-mail" value="{{ $collection->email }}" />
                </div>
                <div class="form-group">
                    <select class="form-control" name="profile">
                        @foreach($profiles as $key => $profile)
                        <option value="{{ $key }}" {{ $collection->profile === $key ? 'selected' : '' }}>
                            {{ $profile }}
                        </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label class="sr-only" for="password"> Senha </label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Alterar senha" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label> Informações biográficas </label>
                    <textarea class="form-control" rows="6" name="description" placeholder="Escreva uma minibiografia para constar no seu perfil. Essas informações poderão ser vistas por todos.">{{ $collection->description }}</textarea>
                </div>
                <div class="form-group">
                    <label class="sr-only" for="linkedin">Linkedin</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-linkedin"></i>
                        </div>
                        <input id="type" name="linkedin" class="form-control input-sm" placeholder="linkedin" value="{{ $collection->linkedin }}">
                        </input>
                    </div>
                </div>
                <div class="form-group">
                    <label class="sr-only" for="twitter">Twitter</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-twitter"></i>
                        </div>
                        <input id="type" name="twitter" class="form-control input-sm" placeholder="twitter" value="{{ $collection->twitter }}">
                        </input>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default btn-flat bg-blue pull-right">
                        Atualizar
                    </button>
                </div>
            </div>
        </panel>
    </form-head>

@stop

@section('script')
    <script>

        $(window).on('load', function() {
        });
    </script>
@stop

@section('css')
<style>
    .img-thumbnail {
        max-width: 30%;
        margin-bottom: 15px;
        border-radius: 50% !important;
        position: absolute;
        left: -35%;
        width: 170px;
        height: 170px;
    }
</style>
@stop

resources/views/admin/user/index.blade.php
@extends('adminlte::page')

@section('title', 'Filipe Cruz - Todos os Usuários')

@section('content_header')
    <title-header title='Usuários'></title-header>
    <breadcrumbs :list="{{ $breadcrumbs }}"></breadcrumbs>
@stop

@section('content')
    <panel title="Gerenciamento de usuários" css="info">
        <box-header create="{{ route('criar.artigos') }}" token="{{ csrf_token() }}"></box-header>
        <data-table
                name="tablePages"
                :titles="[['#', ''],['Nome','string'],[ 'Email',''],['Perfil','']]"
                :content="{{ json_encode($collection) }}"
                edit="{{ route('usuarios') }}"
                exclude="{{ route('usuarios') }}"
                token="{{ csrf_token() }}"
        ></data-table>
        <div class="box-footer clearfix">
            <div class="float-right my-2">
                <div class="pull-right">
                    {{ $collection->links() }}
                </div>
            </div>
        </div>
    </panel>

@stop